### ISSUE TITLE
Split up install and update

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gdm#37]
Where, `update` has the current behavior and `install` will use the last known SHA.

**Comment by jacebrowning** [comment]
Consider adding a `sources_locked` section to the configuration file:

```yaml
...
sources_locked:
- repo: https://github.com/jacebrowning/gdm-demo
  dir: gdm_1
  rev: e6c67f32be788a503373c4a8f02ed132f7a3a8ce
  sources_locked:
  - repo: https://github.com/jacebrowning/gdm-demo
    rev: e6c67f32be788a503373c4a8f02ed132f7a3a8ce
  - repo: https://github.com/jacebrowning/gdm-demo
    rev: e6c67f32be788a503373c4a8f02ed132f7a3a8ce
    sources_locked:
    ...
```
